name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - iblrigv8
    paths:
      - '.github/workflows/documentation.yaml'
      - 'docs/**'
      - 'iblrig/__init__.py'
      - 'CHANGELOG.md'
      - 'README.md'
      - 'pyproject.toml'
permissions:
    contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version-file: pyproject.toml
      - name: Install requirements
        run: pdm sync -dG doc
      - name: Install PortAudio and GraphViz
        run: sudo apt-get install -y libportaudio2 graphviz
      - name: Sphinx build
        run: pdm run sphinx-build docs/source docs/build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
